[package]
name = "sudoku_web"
version = "0.1.0"
authors = ["Martin-Louis Bright <mlbright@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
sudoku = { git = "https://github.com/mlbright/sudoku-norvig-rs" }
js-sys = "0.3.55"